config/routes.rb
Rails.application.routes.draw do
  root 'users#show'
  devise_for :users

  resources :users do
    resources :vehicles do
      resources :park_records, only: [:new, :create, :edit, :update]
    end
  end

  resources :locations do
    resources :slots do
    end
    resources :park_records, only: [:index, :new, :create]
    get '/park_records/simulate', to: 'park_records#simulate', as: :simulate_parking
    post '/park_records/park', to: 'park_records#park', as: :use_slots
    put '/park_records/leave', to: 'park_records#leave', as: :leave_slots
  end
end

app/models/park_record.rb
class ParkRecord < ActiveRecord::Base
  belongs_to :vehicle
  belongs_to :slot

  scope :by_vehicle, -> (vehicle_id) { where("vehicle_id = ?", "#{vehicle_id}") }
  scope :by_slot, -> (slot_id) { where("slot_id = ?", "#{slot_id}") }
  scope :by_location, -> (location_id) { joins(:slot).where("slots.location_id = ?", "#{location_id}")}
  scope :occupied, -> { where(exit_date: nil) }

  def calculate_total
    current_date_time = DateTime.now
    ((current_date_time.to_i - entry_date.to_i) / 1.hours) * Slot::HOURLY_RATE
  end

  def self.total_for_location(location_id)
    by_location(location_id).sum(:total)
  end

  def self.total_vehicles_for_location(location_id)
    by_location(location_id).map(&:vehicle).uniq.count
  end

  def vehicle_vin
    vehicle.vin
  end

  def slot_id
    slot.id
  end
end

app/controllers/park_records_controller.rb
class ParkRecordsController < ApplicationController
  before_action :vehicle, :slot, :location

  def index
    @park_record_presenter = ParkRecordPresenter.new(vehicles, slots, location)
    flash[:error] = 'No parking records registered for this location.' if @park_record_presenter.park_records_for_location.empty?
  end

  def simulate
    @park_record = ParkRecord.new
  end

  def park
    park_record_presenter = ParkRecordPresenter.new(vehicles, slots, location)
    if park_record_presenter.create_park_records
      flash[:success] = 'Parking Records created successfully.'
      redirect_to location_slots_path(@location)
    else  private :occupied_slots_for_location
      flash[:error] = "Some errors when creating parking records."
      render 'new'
    end
  end

  def edit

  end

  def leave
    park_record_presenter = ParkRecordPresenter.new(vehicles, slots, location)
    if park_record_presenter.update_park_records
      flash[:success] = 'Parking Records updated successfully.'
      redirect_to location_slots_path(@location)
    else
      flash[:error] = "Some errors when updating parking records."
      render 'index'
    end
  end

  def location
    @location = Location.find_by_id(params[:location_id])
  end
  private :location

  def vehicle
    @vehicle = Vehicle.find_by_id(params[:vehicle_id]) if params[:vehicle_id]
  end
  private :vehicle

  def slot
    @slot = Slot.find_by_id(params[:slot_id]) if params[:slot_id]
  end
  private :slot

  def slots
    @slots ||= Slot.by_location(location.id)
  end
  private :slots

  def vehicles
    @vehicles ||= Vehicle.all
  end
  private :vehicles

  def park_record_params
    params.require(:park_record).permit(:id,
                                        :vehicle_id,
                                        :slot_id,
                                        :entry_date,
                                        :exit_date,
                                        :comments,
                                        :total)
  end
  private :park_record_params
end

app/views/park_records/index.html.erb
<div class="row">
  <div class="col-md-2">
    <%= render partial: "layouts/user_menu" %>
  </div>
  <div class="col-md-10">

    <div class="row">
      <div class="col-md-2">
      </div>
      <div class="col-md-8">
        <h4>Parking History for <%= @park_record_presenter.name %></h4>
      </div>
      <div class="col-md-2">
      </div>
    </div>
    <div class="row">
      <div class="table-striped table-responsive">
        <table class="table">
          <thead>
            <tr>
              <th>
                Car VIN
              </th>
              <th>
                Slot Id
              </th>
              <th>
                Entry Date
              </th>
              <th>
                Exit Date
              </th>
              <th>
                Total
              </th>
            </tr>
          </thead>
          <tbody>
            <% @park_record_presenter.park_records_for_location.each do |record|%>
              <tr>
                <td><%= record.vehicle_vin %></td>
                <td><%= record.slot_id %></td>
                <td><%= record.entry_date %></td>
                <td><%= record.exit_date %></td>
                <td><%= record.total %></td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
    <div class="row">
      Reports at <h4><%= DateTime.now %></h4>
      <div class="table-striped table-responsive">
        <table class="table">
          <thead>
            <tr>
              <th>
                Total Vehicles
              </th>
              <th>
                Total Ammount
              </th>
              <th>
                Occupied Slots
              </th>
              <th>
                Empty Slots
              </th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td>  <%= @park_record_presenter.total_vehicles_for_location %> Vehicles</td>
              <td> $ <%= @park_record_presenter.total_ammount_for_location %></td>
              <td> <%= @park_record_presenter.occupied_slots_for_location.count %> / <%= @park_record_presenter.slots.count %></td>
              <td> <%= @park_record_presenter.empty_slots_for_location.count %> / <%= @park_record_presenter.slots.count %> </td>
            </tr>
          </tbody>
        </table>
      </div>
    </div>
    <div class="row">
      <div class="col-md-2 button-opt">
        <%= link_to "Slots",
            location_slots_path(@park_record_presenter.location),
            class: 'btn btn-success'%>
      </div>
      <div class="col-md-10">
      </div>
    </div>
  </div>
</div>

app/views/park_records/simulate.html.erb
<div class="row" >
  <div class="col-md-2">
    <%= render partial: "layouts/user_menu" %>
  </div>
  <div class="col-md-6">
    <h3 class="text-center"> New Parking Records for <%= @location.name %> slots </h3>
  </div>
  <div class="col-md-4">

  </div>
</div>
<div class="row">
  <div class="col-md-3">

  </div>
  <div class="col-md-3">
    <%= form_tag location_use_slots_path(@location), method: 'post' do %>
      <div class="form-group">
        <%= submit_tag "Cars are parking", class: 'btn btn-primary'%>
      </div>
    <% end %>
  </div>
  <div class="col-md-3">
    <%= form_tag location_leave_slots_path(@location), method: 'put' do %>
      <div class="form-group">
        <%= submit_tag "Cars are leaving", class: 'btn btn-warning'%>
      </div>
    <% end %>
  </div>
  <div class="col-md-3">
    <div class="form-group">
      <%= link_to "Cancel", location_slots_path(@location), class: 'btn btn-default'%>
    </div>
  </div>
</div>