config/routes.rb
Rails.application.routes.draw do
  root 'users#show'
  devise_for :users

  resources :users do
    resources :vehicles do
      resources :park_records, only: [:new, :create, :edit, :update]
    end
  end

  resources :locations do
    resources :slots do
    end
    resources :park_records, only: [:index, :new, :create]
    get '/park_records/simulate', to: 'park_records#simulate', as: :simulate_parking
    post '/park_records/park', to: 'park_records#park', as: :use_slots
    put '/park_records/leave', to: 'park_records#leave', as: :leave_slots
  end
end

app/views/layouts/_flash_messages.html.erb
<% flash.each do |type, message| %>
  <div class="alert <%= alert_class_for(type) %> alert-dismissible fade in">
    <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
    <%= message %>
  </div>
<% end %>

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    Síganos en <a href="https://twitter.com/?lang=es">Twitter</a>
    y <a href="https://www.facebook.com/">Facebook</a>
  </small>
  <nav>
    <ul>
      <li><%= link_to "Acerca De",   '#' %></li>
      <li><%= link_to "Contáctenos", '#' %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-inverse">
  <div class="container">
    <nav>
      <ul class="nav navbar-nav navbar-right">

        <p class="navbar-text pull-right">
        <% if user_signed_in? %>
          Logged in as <strong><%= current_user.email %></strong>.
          <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
          <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
        <% else %>
          <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
          <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
        <% end %>

      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_user_menu.html.erb
<!-- Single button -->
<div class="btn-group">
  <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
    Menu <span class="caret"></span>
  </button>
  <ul class="dropdown-menu">
    <li><%= link_to "Vehicles", user_vehicles_path(current_user)%></li>
    <li><%= link_to "Reservations" %></li>
    <li><%= link_to "Account" %></li>
    <% if current_user.is_admin? %>
      <li><%= link_to "Users", users_path%></li>
      <li><%= link_to "Locations", locations_path%></li>
      <li><%= link_to "Settings" %></li>
      <li><%= link_to "History" %></li>
    <% end %>
  </ul>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en-US">
  <head>
    <title>Parking System</title>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', params[:controller], 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <%= render partial: "layouts/header" %>
    <div class="container">
      <%= render partial: "layouts/flash_messages", flash: flash %>
      <%= yield %>
      <%= render 'layouts/footer' %>
    </div>
  </body>
</html>